### ISSUE TITLE
Need authentication to run firebase

### ISSUE THREAD

**Issue by tomoakley** [tobyroworth/Crown-PA-Docs-Site#53]
When running `firebase serve`, the console reports this:

````
Visit this URL on any device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=206911858&redirect_uri=http%3A%2F%2Flocalhost%3A9005

Waiting for authentication...
````

It automatically loads the Google oAuth page above and waits for a login to be entered (which I don't have!).

**Comment by tobyroworth** [comment]
This looks like an issue with `firebase-tools` itself - I'll have a look if there's a proper fix for it.

### Workaround 1

create a firebase account

### Workaround 2

use `polymer serve` or any other basic local server. (in `polymer-cli`)

The site will work, except for deep-linking (see #36 and #37).

Deep linking should work once the service worker is activated, as it intercepts requests to any path with `^/docs` and sends the index down

**Comment by tobyroworth** [comment]
This is a _feature_ of `firebase-tools` now:

https://github.com/firebase/firebase-tools/issues/302

I'm guessing workaround 1 doesn't work unless you are a site admin?

Short-term fix will be to use superstatic:

https://github.com/firebase/superstatic

Ideally this will be handled by a gulp task (`gulp serve`) which will build/update a superstatic config file from the firebase config (this might just be a case of taking out the `hosting` object. It could also check for firebase credentials/similar, and only use superstatic as a fallback?

[`var client = require('firebase-tools');`](https://github.com/firebase/firebase-tools#using-as-a-module)

Long-term fix will likely involve a proper express server, to enable SSR as per #37
